/*
		[ Cross-Compilation Support ]

	Architecture Based Lib
*/
#pragma once

typedef struct {
    int sec, nsec;
} sleep_t;

#if defined(__x86__) || defined(__i386__)
	#define MAX_REGISTER 6
	#define SYSCALL_REG "eax"
	#define EXECUTE_SYSCALL "int $0x80"

    // C-ABIV Calling Conventions
    #define __EAX__ "eax"
    #define __EBX__ "ebx"
    #define __ECX__ "ecx"
    #define __EDX__ "edx"
    #define __ESI__ "esi"
    #define __EDI__ "edi"

    #define __EBP__ "ebp"
    #define __ESP__ "esp"

	/* x86 syscall */
	#define _SYS_EXIT 					1
	#define _SYS_FORK					2
	#define _SYS_READ					3
	#define _SYS_WRITE					4
	#define _SYS_OPEN					5
	#define _SYS_CLOSE					6
	#define _SYS_WAITPID				7
	#define _SYS_CREAT					8
	#define _SYS_LINK					9
	#define _SYS_UNLINK					10
	#define _SYS_EXECVE					11
	#define _SYS_CHDIR					12
	#define _SYS_TIME					13
	#define _SYS_MKNOD					14
	#define _SYS_CHMOD					15
	#define _SYS_LCHOWN16				16
	#define _SYS_BREAK					-1
	#define _SYS_OLDSTAT				18
	#define _SYS_LSEEK					19
	#define _SYS_MOUNT					20
	#define _SYS_GETPID					21
	#define _SYS_UMOUNT					22
	#define _SYS_SETUID					23
	#define _SYS_GETUID					24
	#define _SYS_STIME					25
	#define _SYS_PTRACE					26
	#define _SYS_ALARM					27
	#define _SYS_OLDFSTAT				28
	#define _SYS_PAUSE					29
	#define _SYS_UTIME					30
	#define _SYS_STTY					-1
	#define _SYS_GTTY					-1
	#define _SYS_ACCESS					33
	#define _SYS_NICE					34
	#define _SYS_FTIME					35
	#define _SYS_SYNC					36
	#define _SYS_KILL					37
	#define _SYS_RENAME					38
	#define _SYS_MKDIR					39
	#define _SYS_RMDIR					40
	#define _SYS_DUP					41
	#define _SYS_PIPE					42
	#define _SYS_TIMES					43
	#define _SYS_PROF					-1
	#define _SYS_BRK					45
	#define _SYS_SETGID					46
	#define _SYS_GETGID					47
	#define _SYS_SIGNAL					48
	#define _SYS_GETEUID				49
	#define _SYS_GETEGID				50
	#define _SYS_ACCT					51
	#define _SYS_UMOUNT2				52
	#define _SYS_LOCK					-1
	#define _SYS_IOCTL					54
	#define _SYS_FCNTL					55
	#define _SYS_MPX					-1
	#define _SYS_PGID					57
	#define _SYS_ULIMIT					-1
	#define _SYS_OLDOLDUNAME			59
	#define _SYS_UMASK					60
	#define _SYS_CHROOT					61
	#define _SYS_USTAT					62
	#define _SYS_DUP2					63
	#define _SYS_GETPPID				64
	#define _SYS_GETPGRP				65
	#define _SYS_SETSID					66
	#define _SYS_SIGACTION				67
	#define _SYS_SGETMASK				68
	#define _SYS_SSETMASK				69
	#define _SYS_SETREUID				70
	#define _SYS_SETREGID				71
	#define _SYS_SIGSUSPEND				72
	#define _SYS_SIGPENDING				73
	#define _SYS_SETHOSTNAME			74
	#define _SYS_SETRLIMIT				75
	#define _SYS_GETRLIMIT				76
	#define _SYS_GETRUSAGE				77
	#define _SYS_GETTIMEOFDAY			78
	#define _SYS_SETTIMEOFDAY			79
	#define _SYS_GETGROUPS				80
	#define _SYS_SETGROUPS				81
	#define _SYS_SELECT					82
	#define _SYS_SYSLINK				83
	#define _SYS_OLDLSTAT				84
	#define _SYS_READLINK				85
	#define _SYS_USELIB					86
	#define _SYS_SWAPON					87
	#define _SYS_REBOOT					88
	#define _SYS_READDIR				89
	#define _SYS_MMAP					90
	#define _SYS_MUNMAP					91
	#define _SYS_SYSLINK                83
	#define _SYS_TRUNCATE        		92
	#define _SYS_FTRUNCATE       		93
	#define _SYS_FCHMOD      			94
	#define _SYS_FCHOWN16        		95
	#define _SYS_GETPRIORITY     		96
	#define _SYS_SETPRIORITY     		97
	#define _UNIMPLEMENTED       		98
	#define _SYS_STATFS      			99
	#define _SYS_FSTATFS     			100
	#define _SYS_IOPERM      			101
	#define _SYS_SOCKETCALL      		102
	#define _SYS_SYSLOG      			103
	#define _SYS_SETITIMER       		104
	#define _SYS_GETITIMER       		105
	#define _SYS_NEWSTAT     			106
	#define _SYS_NEWLSTAT        		107
	#define _SYS_NEWFSTAT        		108
	#define _SYS_UNAME       			109
	#define _SYS_IOPL        			110
	#define _SYS_VHANGUP     			111
	#define _UNIMPLEMENTED       		112
	#define _NOTFOUND        			113
	#define _SYS_WAIT4       			114
	#define _SYS_SWAPOFF     			115
	#define _SYS_SYSINFO     			116
	#define _SYS_IPC     				117
	#define _SYS_FSYNC       			118
	#define _NOTFOUND        			119
	#define _SYS_CLONE       			120
	#define _SYS_SETDOMAINNAME       	121
	#define _SYS_NEWUNAME        		122
	#define _SYS_MODIFY_LDT      		123
	#define _SYS_ADJTIMEX_TIME32     	124
	#define _SYS_MPROTECT        		125
	#define _SYS_SIGPROCMASK     		126
	#define _UNIMPLEMENTED       		127
	#define _SYS_INIT_MODULE     		128
	#define _SYS_DELETE_MODULE       	129
	#define _UNIMPLEMENTED       		130
	#define _SYS_QUOTACTL        		131
	#define _SYS_GETPGID     			132
	#define _SYS_FCHDIR      			133
	#define _SYS_NI_SYSCALL      		134
	#define _SYS_SYSFS       			135
	#define _SYS_PERSONALITY     		136
	#define _UNIMPLEMENTED       		137
	#define _SYS_SETFSUID16      		138
	#define _SYS_SETFSGID16      		139
	#define _SYS_LLSEEK      			140
	#define _SYS_GETDENTS        		141
	#define _SYS_SELECT      			142
	#define _SYS_FLOCK       			143
	#define _SYS_MSYNC       			144
	#define _SYS_READV       			145
	#define _SYS_WRITEV      			146
	#define _SYS_GETSID      			147
	#define _SYS_FDATASYNC       		148
	#define _SYS_NI_SYSCALL      		149
	#define _SYS_MLOCK       			150
	#define _SYS_MUNLOCK     			151
	#define _SYS_MLOCKALL        		152
	#define _SYS_MUNLOCKALL      		153
	#define _SYS_SCHED_SETPARAM      	154
	#define _SYS_SCHED_GETPARAM      	155
	#define _SYS_SCHED_SETSCHEDULER     156
	#define _SYS_SCHED_GETSCHEDULER     157
	#define _SYS_SCHED_YIELD     		158
	#define _SYS_SCHED_GET_PRIORITY_MAX 159
	#define _SYS_SCHED_GET_PRIORITY_MIN 160
	#define _SYS_SCHED_RR_GET_INTERVAL_TIME 161
	#define _SYS_NANOSLEEP_TIME       	162
	#define _SYS_MREMAP      			163
	#define _SYS_SETRESUID     			164
	#define _SYS_GETRESUID     			165
	#define _NOTFOUND        			166
	#define _UNIMPLEMENTED       		167
	#define _SYS_POLL        			168
	#define _UNIMPLEMENTED       		169
	#define _SYS_SETRESGID16     		170
	#define _SYS_GETRESGID16     		171
	#define _SYS_PRCTL       			172
	#define _SYS_RT_SIGRETURN        	173
	#define _SYS_RT_SIGACTION        	174
	#define _SYS_RT_SIGPROCMASK      	175
	#define _SYS_RT_SIGPENDING       	176
	#define _SYS_RT_SIGTIMEDWAIT_TIME32 177
	#define _SYS_RT_SIGQUEUEINFO     	178
	#define _SYS_RT_SIGSUSPEND       	179
	#define _SYS_IA32_PREAD64        	180
	#define _SYS_IA32_PWRITE64       	181
	#define _SYS_CHOWN16     			182
	#define _SYS_GETCWD      			183
	#define _SYS_CAPGET      			184
	#define _SYS_CAPSET      			185
	#define _SYS_SIGALTSTACK     		186
	#define _SYS_SENDFILE        		187
	#define _UNIMPLEMENTED       		188
	#define _UNIMPLEMENTED       		189
	#define _SYS_VFORK       			190
	#define _SYS_GETRLIMIT       		191
	#define _SYS_MMAP_PGOFF      		192
	#define _SYS_IA32_TRUNCATE64     	193
	#define _SYS_IA32_FTRUNCATE64       194
	#define _SYS_STAT64      			195
	#define _SYS_LSTAT64     			196
	#define _SYS_FSTAT64     			197
	#define _SYS_LCHOWN      			198
	#define _SYS_GETUID      			199
	#define _SYS_GETGID      			200
	#define _SYS_GETEUID     			201
	#define _SYS_GETEGID     			202
	#define _SYS_SETREUID        		203
	#define _SYS_SETREGID        		204
	#define _SYS_GETGROUPS       		205
	#define _SYS_SETGROUPS       		206
	#define _SYS_FCHOWN      			207
	#define _SYS_SETRESUID       		208
	#define _SYS_GETRESUID       		209
	#define _SYS_SETRESGID       		210
	#define _SYS_GETRESGID       		211
	#define _SYS_CHOWN       			212
	#define _SYS_SETUID      			213
	#define _SYS_SETGID      			214
	#define _SYS_SETFSUID        		215
	#define _SYS_SETFSGID        		216
	#define _SYS_PIVOT_ROOT      		217
	#define _SYS_MINCORE     			218
	#define _SYS_MADVISE     			219
	#define _SYS_GETDENTS64      		220
	#define _SYS_FCNTL64     			221
	#define _SYS_GETTID      			224
	#define _SYS_IA32_READAHEAD      	225
	#define _SYS_SETXATTR        		226
	#define _SYS_LSETXATTR       		227
	#define _SYS_FSETXATTR       		228
	#define _SYS_GETXATTR        		229
	#define _SYS_LGETXATTR       		230
	#define _SYS_FGETXATTR       		231
	#define _SYS_LISTXATTR       		232
	#define _SYS_LLISTXATTR      		233
	#define _SYS_FLISTXATTR      		234
	#define _SYS_REMOVEXATTR     		235
	#define _SYS_LREMOVEXATTR        	236
	#define _SYS_FREMOVEXATTR        	237
	#define _SYS_TKILL       			238
	#define _SYS_SENDFILE64      		239
	#define _SYS_FUTEX_TIME32        	240
	#define _SYS_SCHED_SETAFFINITY      241
	#define _SYS_SCHED_GETAFFINITY      242
	#define _SYS_SET_THREAD_AREA     	243
	#define _SYS_GET_THREAD_AREA     	244
	#define _SYS_IO_SETUP        		245
	#define _SYS_IO_DESTROY      		246
	#define _SYS_IO_GETEVENTS_TIME32    247
	#define _SYS_IO_SUBMIT       		248
	#define _SYS_IO_CANCEL       		249
	#define _SYS_IA32_FADVISE64      	250
	#define _SYS_EXIT_GROUP      		252
	#define _NOTFOUND        			253
	#define _SYS_EPOLL_CREATE        	254
	#define _SYS_EPOLL_CTL       		255
	#define _SYS_EPOLL_WAIT      		256
	#define _SYS_REMAP_FILE_PAGES       257
	#define _SYS_SET_TID_ADDRESS     	258
	#define _SYS_TIMER_CREATE        	259
	#define _SYS_TIMER_SETTIME32     	260
	#define _SYS_TIMER_GETTIME32     	261
	#define _SYS_TIMER_GETOVERRUN       262
	#define _SYS_TIMER_DELETE        	263
	#define _SYS_CLOCK_SETTIME32     	264
	#define _SYS_CLOCK_GETTIME32     	265
	#define _SYS_CLOCK_GETRES_TIME32    266
	#define _SYS_CLOCK_NANOSLEEP_TIME32 267
	#define _SYS_STATFS64        		268
	#define _SYS_FSTATFS64       		269
	#define _SYS_TGKILL      			270
	#define _SYS_UTIMES_TIME32       	271
	#define _SYS_IA32_FADVISE64_64      272
	#define _UNIMPLEMENTED       		273
	#define _SYS_MBIND       			274
	#define _SYS_GET_MEMPOLICY       	275
	#define _SYS_SET_MEMPOLICY       	276
	#define _SYS_MQ_OPEN     			277
	#define _SYS_MQ_UNLINK       		278
	#define _SYS_MQ_TIMEDSEND_TIME32    279
	#define _SYS_MQ_TIMEDRECEIVE_TIME32 280
	#define _SYS_MQ_NOTIFY       		281
	#define _SYS_MQ_GETSETATTR       	282
	#define _SYS_KEXEC_LOAD      		283
	#define _SYS_WAITID      			284
	#define _SYS_ADD_KEY     			286
	#define _SYS_REQUEST_KEY     		287
	#define _SYS_KEYCTL      			288
	#define _SYS_IOPRIO_SET      		289
	#define _SYS_IOPRIO_GET      		290
	#define _SYS_INOTIFY_INIT        	291
	#define _SYS_INOTIFY_ADD_WATCH      292
	#define _SYS_INOTIFY_RM_WATCH       293
	#define _SYS_MIGRATE_PAGES       	294
	#define _SYS_OPENAT      			295
	#define _SYS_MKDIRAT     			296
	#define _SYS_MKNODAT     			297
	#define _SYS_FCHOWNAT        		298
	#define _SYS_FUTIMESAT_TIME32       299
	#define _SYS_FSTATAT64       		300
	#define _SYS_UNLINKAT        		301
	#define _SYS_RENAMEAT        		302
	#define _SYS_LINKAT      			303
	#define _SYS_SYMLINKAT       		304
	#define _SYS_READLINKAT      		305
	#define _SYS_FCHMODAT        		306
	#define _SYS_FACCESSAT       		307
	#define _SYS_PSELECT6_TIME32     	308
	#define _SYS_PPOLL_TIME32        	309
	#define _SYS_UNSHARE     			310
	#define _SYS_SET_ROBUST_LIST     	311
	#define _SYS_GET_ROBUST_LIST     	312
	#define _SYS_SPLICE      			313
	#define _SYS_IA32_SYNC_FILE_RANGE   314
	#define _SYS_TEE     				315
	#define _SYS_VMSPLICE        		316
	#define _SYS_MOVE_PAGES      		317
	#define _SYS_GETCPU      			318
	#define _SYS_EPOLL_PWAIT     		319
	#define _SYS_UTIMENSAT_TIME32       320
	#define _SYS_SIGNALFD        		321
	#define _SYS_TIMERFD_CREATE      	322
	#define _SYS_EVENTFD     			323
	#define _SYS_IA32_FALLOCATE      	324
	#define _SYS_TIMERFD_SETTIME32      325
	#define _SYS_TIMERFD_GETTIME32      326
	#define _SYS_SIGNALFD4       		327
	#define _SYS_EVENTFD2        		328
	#define _SYS_EPOLL_CREATE1       	329
	#define _SYS_DUP3        			330
	#define _SYS_PIPE2       			331
	#define _SYS_INOTIFY_INIT1       	332
	#define _SYS_PREADV      			333
	#define _SYS_PWRITEV     			334
	#define _SYS_RT_TGSIGQUEUEINFO      335
	#define _SYS_PERF_EVENT_OPEN     	336
	#define _SYS_RECVMMSG_TIME32     	337
	#define _SYS_FANOTIFY_INIT       	338
	#define _SYS_FANOTIFY_MARK       	339
	#define _SYS_PRLIMIT64       		340
	#define _SYS_NAME_TO_HANDLE_AT      341
	#define _SYS_OPEN_BY_HANDLE_AT      342
	#define _SYS_CLOCK_ADJTIME32     	343
	#define _SYS_SYNCFS      			344
	#define _SYS_SENDMMSG        		345
	#define _SYS_SETNS       			346
	#define _SYS_PROCESS_VM_READV       347
	#define _SYS_PROCESS_VM_WRITEV      348
	#define _SYS_KCMP        			349
	#define _SYS_FINIT_MODULE        	350
	#define _SYS_SCHED_SETATTR       	351
	#define _SYS_SCHED_GETATTR       	352
	#define _SYS_RENAMEAT2       		353
	#define _SYS_SECCOMP     			354
	#define _SYS_GETRANDOM       		355
	#define _SYS_MEMFD_CREATE        	356
	#define _SYS_BPF     				357
	#define _SYS_EXECVEAT        		358
	#define _SYS_SOCKET      			359
	#define _SYS_SOCKETPAIR      		360
	#define _SYS_BIND        			361
	#define _SYS_CONNECT     			362
	#define _SYS_LISTEN      			363
	#define _SYS_ACCEPT4     			364
	#define _SYS_GETSOCKOPT      		365
	#define _SYS_SETSOCKOPT      		366
	#define _SYS_GETSOCKNAME     		367
	#define _SYS_GETPEERNAME     		368
	#define _SYS_SENDTO      			369
	#define _SYS_SENDMSG     			370
	#define _SYS_RECVFROM        		371
	#define _SYS_RECVMSG     			372
	#define _SYS_SHUTDOWN        		373
	#define _SYS_USERFAULTFD     		374
	#define _SYS_MEMBARRIER      		375
	#define _SYS_MLOCK2      			376
	#define _SYS_COPY_FILE_RANGE     	377
	#define _SYS_PREADV2     			378
	#define _SYS_PWRITEV2        		379
	#define _SYS_PKEY_MPROTECT       	380
	#define _SYS_PKEY_ALLOC      		381
	#define _SYS_PKEY_FREE       		382
	#define _SYS_STATX       			383
	#define _SYS_ARCH_PRCTL      		384
	#define _SYS_IO_PGETEVENTS_TIME32   385
	#define _SYS_RSEQ        			386
	#define _SYS_SEMGET      			393
	#define _SYS_SEMCTL      			394
	#define _SYS_SHMGET      			395
	#define _SYS_SHMCTL      			396
	#define _SYS_SHMAT       			397
	#define _SYS_SHMDT       			398
	#define _SYS_MSGGET      			399
	#define _SYS_MSGSND      			400
	#define _SYS_MSGRCV      			401
	#define _SYS_MSGCTL      			402
	#define _SYS_CLOCK_GETTIME       	403
	#define _SYS_CLOCK_SETTIME       	404
	#define _SYS_CLOCK_ADJTIME       	405
	#define _SYS_CLOCK_GETRES       	406
	#define _SYS_CLOCK_NANOSLEEP     	407
	#define _SYS_TIMER_GETTIME       	408
	#define _SYS_TIMER_SETTIME       	409
	#define _SYS_TIMERFD_GETTIME     	410
	#define _SYS_TIMERFD_SETTIME     	411
	#define _SYS_UTIMENSAT       		412
	#define _SYS_PSELECT6        		413
	#define _SYS_PPOLL       			414
	#define _SYS_IO_PGETEVENTS       	416
	#define _SYS_RECVMMSG        		417
	#define _SYS_MQ_TIMEDSEND        	418
	#define _SYS_MQ_TIMEDRECEIVE     	419
	#define _SYS_SEMTIMEDOP      		420
	#define _SYS_RT_SIGTIMEDWAIT     	421
	#define _SYS_FUTEX       			422
	#define _SYS_SCHED_RR_GET_INTERVAL  423
	#define _SYS_PIDFD_SEND_SIGNAL      424
	#define _SYS_IO_URING_SETUP      	425
	#define _SYS_IO_URING_ENTER      	426
	#define _SYS_IO_URING_REGISTER      427
	#define _SYS_OPEN_TREE       		428
	#define _SYS_MOVE_MOUNT      		429
	#define _SYS_FSOPEN      			430
	#define _SYS_FSCONFIG        		431
	#define _SYS_FSMOUNT     			432
	#define _SYS_FSPICK      			433
	#define _SYS_PIDFD_OPEN      		434
	#define _SYS_CLONE3      			435
	#define _SYS_CLOSE_RANGE     		436
	#define _SYS_OPENAT2     			437
	#define _SYS_PIDFD_GETFD     		438
	#define _SYS_FACCESSAT2      		439
	#define _SYS_PROCESS_MADVISE     	440
	#define _SYS_EPOLL_PWAIT2        	441
	#define _SYS_MOUNT_SETATTR      	442
	#define _SYS_QUOTACTL_FD     		443
	#define _SYS_LANDLOCK_CREATE_RULESET 444
	#define _SYS_LANDLOCK_ADD_RULE      445
	#define _SYS_LANDLOCK_RESTRICT_SELF 446
	#define _SYS_MEMFD_SECRET        	447
	#define _SYS_PROCESS_MRELEASE       448
	#define _SYS_FUTEX_WAITV     		449
	#define _SET_MEMPOLICY_HOME_NOD		-1
#elif defined(__x86_64__)
	#define MAX_REGISTER 6
	#define SYSCALL_REG "rax"
	#define EXECUTE_SYSCALL "syscall"

	/* x86_64 C-ABIV Calling Convension */
    #define __RAX__ "rax"
    #define __RDI__ "rdi"
    #define __RSI__ "rsi"
    #define __RDX__ "rdx"
    #define __R10__ "r10"
    #define __R8__ "r8"
    #define __R9__ "r9"
    #define __RBX__ "rbx"
    #define __RCX__ "rcx"
    #define __RBP__ "rbp"
    #define __R15__ "r15"
    #define __R14__ "r14"
    #define __R13__ "r13"
    #define __R12__ "r12"
    #define __R11__ "r11"
    #define __RSP__ "rsp"

	/* x86_64 syscalls */
    #define _SYS_READ                   0
    #define _SYS_WRITE                  1
    #define _SYS_OPEN                   2
    #define _SYS_CLOSE                  3
    #define _SYS_STAT                   4
    #define _SYS_FSTAT                  5
    #define _SYS_LSTAT                  6
    #define _SYS_POLL                   7
    #define _SYS_LSEEK                  8
    #define _SYS_MMAP                   9
    #define _SYS_MPROTECT               10
    #define _SYS_MUNMAP                 11
    #define _SYS_BRK                    12
    #define _SYS_RT_SIGACTION           13
    #define _SYS_RT_SIGPROCMASK         14
    #define _SYS_RT_SIGRETURN           15
    #define _SYS_IOCTL                  16
    #define _SYS_PREAD64                17
    #define _SYS_PWRITE64               18
    #define _SYS_READV                  19
    #define _SYS_WRITEV                 20
    #define _SYS_ACCESS                 21
    #define _SYS_PIPE                   22
    #define _SYS_SELECT                 23
    #define _SYS_SCHED_YIELD            24
    #define _SYS_MREMAP                 25
    #define _SYS_MSYNC                  26
    #define _SYS_MINCORE                27
    #define _SYS_MADVISE                28
    #define _SYS_SHMGET                 29
    #define _SYS_SHMAT                  30
    #define _SYS_SHMTL                  31
    #define _SYS_DUP                    32
    #define _SYS_DUP2                   33
    #define _SYS_PAUSE                  34
    #define _SYS_NANOSLEEP              35
    #define _SYS_GETITIMER              36
    #define _SYS_ALARM                  37
    #define _SYS_SETITIMER              38
    #define _SYS_GETPID                 39
    #define _SYS_SENDFILE               40
    #define _SYS_SOCKET                 41
    #define _SYS_CONNECT                42
    #define _SYS_ACCEPT                 43
    #define _SYS_SENDTO                 44
    #define _SYS_RECVFROM               45
    #define _SYS_SENDMSG                46
    #define _SYS_RECVMSG                47
    #define _SYS_SHUTDOWN               48
    #define _SYS_BIND                   49
    #define _SYS_LISTEN                 50
    #define _SYS_GETSOCKNAME            51
    #define _SYS_GETPEERNAME            52
    #define _SYS_SOCKETPAIR             53
    #define _SYS_SETSOCKOPT             54
    #define _SYS_GETSOCKOPT             55
    #define _SYS_CLONE                  56
    #define _SYS_FORK                   57
    #define _SYS_VFORK                  58
    #define _SYS_EXECVE                 59
    #define _SYS_EXIT                   60
    #define _SYS_WAIT4                  61
    #define _SYS_KILL                   62
    #define _SYS_UNAME                  63
    #define _SYS_SEMGET                 64
    #define _SYS_SEMOP                  65
    #define _SYS_SEMCTL                 66
    #define _SYS_SHMDT                  67
    #define _SYS_MSGGET                 68
    #define _SYS_MSGSND                 69
    #define _SYS_MSGRCV                 70
    #define _SYS_MSGCTL                 71
    #define _SYS_FCNTL                  72
    #define _SYS_FLOCK                  73
    #define _SYS_FSYNC                  74
    #define _SYS_FDATASYNC              75
    #define _SYS_TRUNCATE               76
    #define _SYS_FTRUNCATE              77
    #define _SYS_GETDENTS               78
    #define _SYS_GETCWD                 79
    #define _SYS_CHDIR                  80
    #define _SYS_FCHDIR                 81
    #define _SYS_RENAME                 82
    #define _SYS_MKDIR                  83
    #define _SYS_RMDIR                  84
    #define _SYS_CREAT                  85
    #define _SYS_LINK                   86
    #define _SYS_UNLINK                 87
    #define _SYS_SYMLINK                88
    #define _SYS_READLINK               89
    #define _SYS_CHMOD                  90
    #define _SYS_FCHMOD                 91
    #define _SYS_CHOWN                  92
    #define _SYS_FCHOWN                 93
    #define _SYS_LCHOWN                 94
    #define _SYS_UMASK                  95
    #define _SYS_GETTIMEOFDAT           96
    #define _SYS_GETRLIMIT              97
    #define _SYS_GETRUSAGE              98
    #define _SYS_SYSINFO                99
    #define _SYS_TIMES                  100
    #define _SYS_PTRACE                 101
    #define _SYS_GETUID                 102
    #define _SYS_SYSLOG                 103
    #define _SYS_GETGID                 104
    #define _SYS_SETUID                 105
    #define _SYS_SETGID                 106
    #define _SYS_GETEUID                107
    #define _SYS_GETEGID                108
    #define _SYS_SETPGID                109
    #define _SYS_GETPPID                110
    #define _SYS_GETPGRP                111
    #define _SYS_SETSID                 112
    #define _SYS_SETREUID               113
    #define _SYS_SETREGID               114
    #define _SYS_GETGROUPS              115
    #define _SYS_SETGROUPS              116
    #define _SYS_SETRESUID              117
    #define _SYS_GETRESUID              118
    #define _SYS_SETRESGID              119
    #define _SYS_GETRESGID              120
    #define _SYS_GETPGID                121
    #define _SYS_SETFSUID               122
    #define _SYS_SETFSGID               123
    #define _SYS_GETSID                 124
    #define _SYS_CAPGET                 125
    #define _SYS_CATSET                 126
    #define _SYS_RT_SIGPENDING          127
    #define _SYS_RT_SIGTIMEDWAIT        128
    #define _SYS_RT_SIGQUEUEINFO        129
    #define _SYS_RT_SIGSUSPEND          130
    #define _SYS_SIGALTSTACK            131
    #define _SYS_UTIME                  132
    #define _SYS_MKNOD                  133
    #define _SYS_USELIB                 134
    #define _SYS_PERSONALITY            135
    #define _SYS_USTAT                  136
    #define _SYS_STATFS                 137
    #define _SYS_FSTATFS                138
    #define _SYS_SYSFS                  139
    #define _SYS_GETPRIORITY            140
    #define _SYS_SETPRIORITY            141
    #define _SYS_SCHED_SETPARAM         142
    #define _SYS_SCHED_GETPARAM         143
    #define _SYS_SCHED_SETSCHEDULER     144
    #define _SYS_SCHED_GETSCHEDULAR     145
    #define _SYS_SCHED_GET_PRIORITY_MAX 146
    #define _SYS_SCHED_GET_PRIORITY_MIN 147
    #define _SYS_SCHED_RR_GET_INTERVAL  148
    #define _SYS_MLOCK                  149
    #define _SYS_MINLOCK                150
    #define _SYS_MLOCKALL               151
    #define _SYS_MUNLOCKALL             152
    #define _SYS_VHANGUP                153
    #define _SYS_MODIFY_LDT             154
    #define _SYS_PIVOT_ROOT             155
    #define _SYS__SYSCTL                156
    #define _SYS_PRCTL                  157
    #define _SYS_ARCH_PRCTL             158
    #define _SYS_ADJTIMEX               159
    #define _SYS_SETRLIMIT              160
    #define _SYS_CHROOT                 161
    #define _SYS_SYNC                   162
    #define _SYS_ACCT                   163
    #define _SYS_SETTIMEOFDAY           164
    #define _SYS_MOUNT                  165
    #define _SYS_UMOUNT2                166
    #define _SYS_SWAPON                 167
    #define _SYS_SWAPOFF                168
    #define _SYS_REBOOT                 169
    #define _SYS_SETHOSTNAME            170
    #define _SYS_SETDOMAINNAME          171
    #define _SYS_IOPL                   172
    #define _SYS_IOPERM                 173
    #define _SYS_CREATE_MODULE          174
    #define _SYS_INIT_MODULE            175
    #define _SYS_DELETE_MODULE          176
    #define _SYS_GET_KERNEL_SYMS        177
    #define _SYS_QUERY_MODULE           178
    #define _SYS_QUOTACTL               179
    #define _SYS_NFSSERVCTL             180
    #define _SYS_GETPMSG                181
    #define _SYS_PUTPMSG                182
    #define _SYS_AFS_SYSCALL            183
    #define _SYS_TUXCALL                184
    #define _SYS_SECURITY               185
    #define _SYS_GETTID                 186
    #define _SYS_READAHEAD              187
    #define _SYS_SETXATTR               188
    #define _SYS_LSETXATTR              189
    #define _SYS_FSETXATTR              190
    #define _SYS_GETXATTR               191
    #define _SYS_LGETXATTR              192
    #define _SYS_FGETXATTR              193
    #define _SYS_LISTXATTR              194
    #define _SYS_LLISTXATTR             195
    #define _SYS_FLISTXATTR             196
    #define _SYS_REMOVEXATTR            197
    #define _SYS_LREMOVEXATTR           198
    #define _SYS_FREMOVEXATTR           199
    #define _SYS_TKILL                  200
    #define _SYS_TIME                   201
    #define _SYS_FUTEX                  202
    #define _SYS_SCHED_SETAFFINITY      203
    #define _SYS_SCHED_GETAFFINITY      204
    #define _SYS_SET_THREAD_AREA        205
    #define _SYS_IO_SETUP               206
    #define _SYS_IO_DESTROY             207
    #define _SYS_IO_GETEVENTS           208
    #define _SYS_IO_SUBMIT              209
    #define _SYS_IO_CANCEL              210
    #define _SYS_GET_THREAD_AREA        211
    #define _SYS_LOOKUP_DCOOKIE         212
    #define _SYS_EPOLL_CREATE           213
    #define _SYS_EPOLL_CTL_OLD          214
    #define _SYS_EPOLL_WAIT_OLD         215
    #define _SYS_REMAP_FILE_PAGES       216
    #define _SYS_GETDENTS64             217
    #define _SYS_SET_TID_ADDRESS        218
    #define _SYS_RESTART_SYSCALL        219
    #define _SYS_SETTIMEDOP             220
    #define _SYS_FADVISE64              221
    #define _SYS_TIMER_CREATE           222
    #define _SYS_TIMER_SETTIME          223
    #define _SYS_TIMER_GETTIME          224
    #define _SYS_TIMER_GETOVERRUN       225
    #define _SYS_TIMER_DELETE           226
    #define _SYS_CLOCK_SETTIME          227
    #define _SYS_CLOCK_GETTIME          228
    #define _SYS_CLOCK_GETRES           229
    #define _SYS_CLOCK_NANOSLEEP        230
    #define _SYS_EXIT_GROUP             231
    #define _SYS_EPOLL_WAIT             232
    #define _SYS_EPOLL_CTL              233
    #define _SYS_TGKILL                 234
    #define _SYS_UTIMES                 235
    #define _SYS_VSERVER                236
    #define _SYS_MBIND                  237
    #define _SYS_SET_MEMPOLICY          238
    #define _SYS_GET_MEMPOLICY          239
    #define _SYS_MQ_OPEN                240
    #define _SYS_MQ_UNLINK              241
    #define _SYS_MQ_TIMEDSEND           242
    #define _SYS_MQ_TIMEDRECEIVE        243
    #define _SYS_MQ_NOTIFY              244
    #define _SYS_MQ_GETSETATTR          245
    #define _SYS_KEXEC_LOAD             246
    #define _SYS_WAITID                 247
    #define _SYS_ADD_KEY                248
    #define _SYS_REQUEST_KEY            249
    #define _SYS_KEYCTL                 250
    #define _SYS_IOPRIO_SET             251
    #define _SYS_IOPRIO_GET             252
    #define _SYS_INOTIFY_INIT           253
    #define _SYS_INOTIFY_ADD_WATCH      254
    #define _SYS_INOTIFY_RM_WATCH       255
    #define _SYS_MIGRATE_PAGES          256
    #define _SYS_OPENAT                 257
    #define _SYS_MKDIRAT                258
    #define _SYS_MKNODAT                259
    #define _SYS_FCHOWNAT               260
    #define _SYS_FUTIMESAY              261
    #define _SYS_NEWFSTATAT             262
    #define _SYS_UNLINKAT               263
    #define _SYS_RENAMEAT               264
    #define _SYS_LINKAT                 265
    #define _SYS_SYMLINKAT              266
    #define _SYS_READLINKAT             267
    #define _SYS_FCHMODAT               268
    #define _SYS_FACCESSAT              269
    #define _SYS_PSELECT6               270
    #define _SYS_PPOLL                  271
    #define _SYS_UNSHARE                272
    #define _SYS_SET_ROBUST_LIST        273
    #define _SYS_GET_ROBUST_LIST        274
    #define _SYS_SPLICE                 275
    #define _SYS_TEE                    276
    #define _SYS_SYNC_FILE_RANGE        277
    #define _SYS_VMSPLICE               278
    #define _SYS_MOVE_PAGES             279
    #define _SYS_UTIMENSAT              280
    #define _SYS_EPOLL_PWAIT            281
    #define _SYS_SIGNALFD               282
    #define _SYS_TIMERFD_CREATE         283
    #define _SYS_EVENTFD                284
    #define _SYS_FALLOCATE              285
    #define _SYS_TIMERFD_SETTIME        286
    #define _SYS_TIMERFD_GETTIME        287
    #define _SYS_ACCEPT4                288
    #define _SYS_SIGNALFD4              289
    #define _SYS_EVENTFD2               290
    #define _SYS_EPOLL_CREATE1          291
    #define _SYS_DUP3                   292
    #define _SYS_PIPE2                  293
    #define _SYS_INOTIFY_INIT1          294
    #define _SYS_PREADV                 295
    #define _SYS_PWRITEV                296
    #define _SYS_RT_TGSIGQUEUEINFO      297
    #define _SYS_PERF_EVENT_OPEN        298
    #define _SYS_RECVMMSG               299
    #define _SYS_FANOTIFY_INIT          300
    #define _SYS_FANOTIFY_MARK          301
    #define _SYS_PRLIMIT64              302
    #define _SYS_NAME_TO_HANDLE_AT      303
    #define _SYS_OPEN_BY_HANDLE_AT      304
    #define _SYS_CLOCK_ADJTIME          305
    #define _SYS_SYNCFS                 306
    #define _SYS_SENDMMSG               307
    #define _SYS_SETNS                  308
    #define _SYS_GETCPU                 309
    #define _SYS_PROCESS_VM_READV       310
    #define _SYS_PROVESS_VM_WRITEV      311
    #define _SYS_KCMP                   312
    #define _SYS_FINIT_MODULE           313
    #define _SYS_SCHED_SETATTR          314
    #define _SYS_SCHED_GETATTR          315
    #define _SYS_RENAMEAT2              316
    #define _SYS_SECCOMP                317
    #define _SYS_GETRANDOM              318
    #define _SYS_MEMFD_CREATE           319
    #define _SYS_KEXEC_FILE_LOAD        320
    #define _SYS_BPF                    321
    #define _STUB_EXECVEAT              322
    #define _USERFAULTFD                323
    #define _MEMBARRIER                 324
    #define _MLOCK2                     325
    #define _COPY_FILE_RANGE            326
    #define _PREADV2                    327
    #define _PWRITEV2                   328
    #define _PKEY_MPROTECT              329
    #define _PKEY_ALLOC                 330
    #define _PKEY_FREE                  331
    #define _STATX                      332
    #define _IO_PGETEVENTS              333
    #define _RSEQ                       334
    #define _PKEY_MPROTECT2             335

	/* x86_64 syscall wrappers */
	long __sys_mmap(long arg1, long arg2, long arg3, long arg4, long arg5, long arg6);

#elif defined(__riscv)
	#define MAX_REGISTER 8
	#define SYSCALL_REG "a7"
	#define EXECUTE_SYSCALL "ecall"

	/* risc-v syscalls */
	#define _IO_SETUP					0
	#define _IO_DESTROY					1
	#define _IO_SUBMIT					2
	#define _IO_CANCEL					3
	#define _IO_GETEVENTS				4
	#define _SETXATTR					5
	#define _LSETXATTR					6
	#define _FSETXATTR					7
	#define _GETXATTR					8
	#define _LGETXATTR					9
	#define _FGETXATTR					10
	#define _LISTXATTR					11
	#define _LLISTXATTR					12
	#define _FLISTXATTR					13
	#define _REMOVEXATTR				14
	#define _LREMOVEXATTR				15
	#define _FREMOVEXATTR				16
	#define _GETCWD						17
	#define _LOOKUP_DCOOKIE				18
	#define _EVENTFD2					19
	#define _EPOLL_CREATE1				20
	#define _EPOLL_CTL					21
	#define _EPOLL_PWAIT				22
	#define _DUP						23
	#define _DUP3						24
	#define _FCNTL64					25
	#define _INOTIFY_INIT1				26
	#define _INOTIFY_ADD_WATCH			27
	#define _INOTIFY_RM_WATCH			28
	#define _IOCTL					 	29
	#define _IOPRIO_SET					30
	#define _IOPRIO_GET					31
	#define _FLOCK					 	32
	#define _MKNODAT					33
	#define _MKDIRAT					34
	#define _UNLINKAT					35
	#define _SYMLINKAT					36
	#define _LINKAT					 	37
	#define _RENAMEAT					38
	#define _UMOUNT					 	39
	#define _MOUNT					 	40
	#define _PIVOT_ROOT					41
	#define _NI_SYSCALL					42
	#define _STATFS64					43
	#define _FSTATFS64					44
	#define _TRUNCATE64					45
	#define _FTRUNCATE64				46
	#define _FALLOCATE					47
	#define _FACCESSAT					48
	#define _CHDIR					 	49
	#define _FCHDIR					 	50
	#define _CHROOT					 	51
	#define _FCHMOD					 	52
	#define _FCHMODAT					53
	#define _FCHOWNAT					54
	#define _FCHOWN					 	55
	#define _OPENAT					 	56
	#define _CLOSE					 	57
	#define _VHANGUP					58
	#define _PIPE2					 	59
	#define _QUOTACTL					60
	#define _GETDENTS64					61
	#define _LSEEK					 	62
	#define _READ					 	63
	#define _WRITE					 	64
	#define _READV					 	65
	#define _WRITEV					 	66
	#define _PREAD64					67
	#define _PWRITE64					68
	#define _PREADV					 	69
	#define _PWRITEV					70
	#define _SENDFILE64					71
	#define _PSELECT6_TIME32			72
	#define _PPOLL_TIME32				73
	#define _SIGNALFD4					74
	#define _VMSPLICE					75
	#define _SPLICE					 	76
	#define _TEE					 	77
	#define _READLINKAT					78
	#define _NEWFSTATAT					79
	#define _NEWFSTAT					80
	#define _SYNC					 	81
	#define _FSYNC					 	82
	#define _FDATASYNC					83
	#define _SYNC_FILE_RANGE2			84
	#define _SYNC_FILE_RANGE			84
	#define _TIMERFD_CREATE				85
	#define _TIMERFD_SETTIME			411
	#define _TIMERFD_GETTIME			410
	#define _UTIMENSAT					412
	#define _ACCT					 	89
	#define _CAPGET					 	90
	#define _CAPSET					 	91
	#define _PERSONALITY				92
	#define _EXIT					 	93
	#define _EXIT_GROUP					94
	#define _WAITID					 	95
	#define _SET_TID_ADDRESS			96
	#define _UNSHARE					97
	#define _FUTEX					 	422
	#define _SET_ROBUST_LIST			99
	#define _GET_ROBUST_LIST			100
	#define _NANOSLEEP					101
	#define _GETITIMER					102
	#define _SETITIMER					103
	#define _KEXEC_LOAD					104
	#define _INIT_MODULE				105
	#define _DELETE_MODULE				106
	#define _TIMER_CREATE				107
	#define _TIMER_GETTIME				408
	#define _TIMER_GETOVERRUN			109
	#define _TIMER_SETTIME				409
	#define _TIMER_DELETE				111
	#define _CLOCK_SETTIME				404
	#define _CLOCK_GETTIME				403
	#define _CLOCK_GETRES				406
	#define _CLOCK_NANOSLEEP			407
	#define _SYSLOG					 	116
	#define _PTRACE					 	117
	#define _SCHED_SETPARAM				118
	#define _SCHED_SETSCHEDULER			119
	#define _SCHED_GETSCHEDULER			120
	#define _SCHED_GETPARAM				121
	#define _SCHED_SETAFFINITY			122
	#define _SCHED_GETAFFINITY			123
	#define _SCHED_YIELD				124
	#define _SCHED_GET_PRIORITY_MAX		125
	#define _SCHED_GET_PRIORITY_MIN		126
	#define _SCHED_RR_GET_INTERVAL		423
	#define _RESTART_SYSCALL			128
	#define _KILL					 	129
	#define _TKILL					 	130
	#define _TGKILL					 	131
	#define _SIGALTSTACK				132
	#define _RT_SIGSUSPEND				133
	#define _RT_SIGACTION				134
	#define _RT_SIGPROCMASK				135
	#define _RT_SIGPENDING				136
	#define _RT_SIGTIMEDWAIT_TIME32		137
	#define _RT_SIGQUEUEINFO			138
	#define _SETPRIORITY				140
	#define _GETPRIORITY				141
	#define _REBOOT					 	142
	#define _SETREGID					143
	#define _SETGID					 	144
	#define _SETREUID					145
	#define _SETUID					 	146
	#define _SETRESUID					147
	#define _GETRESUID					148
	#define _SETRESGID					149
	#define _GETRESGID					150
	#define _SETFSUID					151
	#define _SETFSGID					152
	#define _TIMES					 	153
	#define _SETPGID					154
	#define _GETPGID					155
	#define _GETSID					 	156
	#define _SETSID					 	157
	#define _GETGROUPS					158
	#define _SETGROUPS					159
	#define _NEWUNAME					160
	#define _SETHOSTNAME				161
	#define _SETDOMAINNAME				162
	#define _GETRLIMIT					163
	#define _SETRLIMIT					164
	#define _GETRUSAGE					165
	#define _UMASK					 	166
	#define _PRCTL					 	167
	#define _GETCPU					 	168
	#define _GETTIMEOFDAY				169
	#define _SETTIMEOFDAY				170
	#define _ADJTIMEX					171
	#define _GETPID					 	172
	#define _GETPPID					173
	#define _GETUID					 	174
	#define _GETEUID					175
	#define _GETGID					 	176
	#define _GETEGID					177
	#define _GETTID					 	178
	#define _SYSINFO					179
	#define _MQ_OPEN					180
	#define _MQ_UNLINK					181
	#define _MQ_TIMEDSEND				418
	#define _MQ_TIMEDRECEIVE			419
	#define _MQ_NOTIFY					184
	#define _MQ_GETSETATTR				185
	#define _MSGGET					 	186
	#define _MSGCTL					 	187
	#define _MSGRCV					 	188
	#define _MSGSND					 	189
	#define _SEMGET					 	190
	#define _SEMCTL					 	191
	#define _SEMTIMEDOP					420
	#define _SEMOP					 	193
	#define _SHMGET					 	194
	#define _SHMCTL					 	195
	#define _SHMAT					 	196
	#define _SHMDT					 	197
	#define _SOCKET					 	198
	#define _SOCKETPAIR					199
	#define _BIND					 	200
	#define _LISTEN					 	201
	#define _ACCEPT					 	202
	#define _CONNECT					203
	#define _GETSOCKNAME				204
	#define _GETPEERNAME				205
	#define _SENDTO					 	206
	#define _RECVFROM					207
	#define _SETSOCKOPT					208
	#define _GETSOCKOPT					209
	#define _SHUTDOWN					210
	#define _SENDMSG					211
	#define _RECVMSG					212
	#define _READAHEAD					213
	#define _BRK					 	214
	#define _MUNMAP					 	215
	#define _MREMAP					 	216
	#define _ADD_KEY					217
	#define _REQUEST_KEY				218
	#define _KEYCTL					 	219
	#define _CLONE					 	220
	#define _EXECVE					 	221
	#define _SYS_MMAP					222
	#define _FADVISE64_64				223
	#define _SWAPON					 	224
	#define _SWAPOFF					225
	#define _MPROTECT					226
	#define _MSYNC					 	227
	#define _MLOCK					 	228
	#define _MUNLOCK					229
	#define _MLOCKALL					230
	#define _MUNLOCKALL					231
	#define _MINCORE					232
	#define _MADVISE					233
	#define _REMAP_FILE_PAGES			234
	#define _MBIND					 	235
	#define _GET_MEMPOLICY				236
	#define _SET_MEMPOLICY				237
	#define _MIGRATE_PAGES				238
	#define _MOVE_PAGES					239
	#define _RT_TGSIGQUEUEINFO			240
	#define _PERF_EVENT_OPEN			241
	#define _ACCEPT4					242
	#define _RECVMMSG_TIME32			243
	#define _WAIT4					 	260
	#define _PRLIMIT64					261
	#define _FANOTIFY_INIT				262
	#define _FANOTIFY_MARK				263
	#define _NAME_TO_HANDLE_AT			264
	#define _OPEN_BY_HANDLE_AT			265
	#define _CLOCK_ADJTIME				405
	#define _SYNCFS					 	267
	#define _SETNS					 	268
	#define _SENDMMSG					269
	#define _PROCESS_VM_READV			270
	#define _PROCESS_VM_WRITEV			271
	#define _KCMP					 	272
	#define _FINIT_MODULE				273
	#define _SCHED_SETATTR				274
	#define _SCHED_GETATTR				275
	#define _RENAMEAT2					276
	#define _SECCOMP					277
	#define _GETRANDOM					278
	#define _MEMFD_CREATE				279
	#define _BPF					 	280
	#define _EXECVEAT					281
	#define _USERFAULTFD				282
	#define _MEMBARRIER					283
	#define _MLOCK2					 	284
	#define _COPY_FILE_RANGE			285
	#define _PREADV2					286
	#define _PWRITEV2					287
	#define _PKEY_MPROTECT				288
	#define _PKEY_ALLOC					289
	#define _PKEY_FREE					290
	#define _STATX					 	291
	#define _IO_PGETEVENTS				416
	#define _RSEQ					 	293
	#define _KEXEC_FILE_LOAD			294
	#define _PIDFD_SEND_SIGNAL			424
	#define _IO_URING_SETUP				425
	#define _IO_URING_ENTER				426
	#define _IO_URING_REGISTER			427
	#define _OPEN_TREE					428
	#define _MOVE_MOUNT					429
	#define _FSOPEN					 	430
	#define _FSCONFIG					431
	#define _FSMOUNT					432
	#define _FSPICK					 	433
	#define _PIDFD_OPEN					434
	#define _CLONE3					 	435
	#define _CLOSE_RANGE				436
	#define _OPENAT2					437
	#define _PIDFD_GETFD				438
	#define _FACCESSAT2					439
	#define _PROCESS_MADVISE			440
#elif defined(__aarch64__)
	#define MAX_REGISTER 8
	#define SYSCALL_REG "x8"
	#define EXECUTE_SYSCALL "svc #0"
#elif defined(__arm__)
	#define MAX_REGISTER 4
	#define SYSCALL_REG "r7"
	#define EXECUTE_SYSCALL "svc #0"
#elif defined(_WIN64)
	#define MAX_REGISTER 4
	#define SYSCALL_REG "rcx"
	#define EXECUTE_SYSCALL "syscall"
#else
	#define MAX_REGISTER 0
	#define SYSCALL_REG 0
	#define EXECUTE_SYSCALL 0
#endif

