/*
		[ Cross-Compilation Support ]

	Architecture Based Lib
*/
#pragma once

typedef struct {
    int sec, nsec;
} sleep_t;

#if defined(__x86__) || defined(__i386__)
	#define MAX_REGISTER 6
	#define SYSCALL_REG "eax"
	#define EXECUTE_SYSCALL "int $0x80"
	
    // C-ABIV Calling Conventions
    #define __EAX__ "eax"
    #define __EBX__ "ebx"
    #define __ECX__ "ecx"
    #define __EDX__ "edx"
    #define __ESI__ "esi"
    #define __EDI__ "edi"

    #define __EBP__ "ebp"
    #define __ESP__ "esp"

	/* x86 syscall */
	#define _SYS_EXIT 					1
	#define _SYS_FORK					2
	#define _SYS_READ					3
	#define _SYS_WRITE					4
	#define _SYS_OPEN					5
	#define _SYS_CLOSE					6
	#define _SYS_WAITPID				7
	#define _SYS_CREAT					8
	#define _SYS_LINK					9
	#define _SYS_UNLINK					10
	#define _SYS_EXECVE					11
	#define _SYS_CHDIR					12
	#define _SYS_TIME					13
	#define _SYS_MKNOD					14
	#define _SYS_CHMOD					15
	#define _SYS_LCHOWN16				16
	#define _SYS_BREAK					-1
	#define _SYS_OLDSTAT				18
	#define _SYS_LSEEK					19
	#define _SYS_MOUNT					20
	#define _SYS_GETPID					21
	#define _SYS_UMOUNT					22
	#define _SYS_SETUID					23
	#define _SYS_GETUID					24
	#define _SYS_STIME					25
	#define _SYS_PTRACE					26
	#define _SYS_ALARM					27
	#define _SYS_OLDFSTAT				28
	#define _SYS_PAUSE					29
	#define _SYS_UTIME					30
	#define _SYS_STTY					-1
	#define _SYS_GTTY					-1
	#define _SYS_ACCESS					33
	#define _SYS_NICE					34
	#define _SYS_FTIME					35
	#define _SYS_SYNC					36
	#define _SYS_KILL					37
	#define _SYS_RENAME					38
	#define _SYS_MKDIR					39
	#define _SYS_RMDIR					40
	#define _SYS_DUP					41
	#define _SYS_PIPE					42
	#define _SYS_TIMES					43
	#define _SYS_PROF					-1
	#define _SYS_BRK					45
	#define _SYS_SETGID					46
	#define _SYS_GETGID					47
	#define _SYS_SIGNAL					48
	#define _SYS_GETEUID				49
	#define _SYS_GETEGID				50
	#define _SYS_ACCT					51
	#define _SYS_UMOUNT2				52
	#define _SYS_LOCK					-1
	#define _SYS_IOCTL					54
	#define _SYS_FCNTL					55
	#define _SYS_MPX					-1
	#define _SYS_PGID					57
	#define _SYS_ULIMIT					-1
	#define _SYS_OLDOLDUNAME			59
	#define _SYS_UMASK					60
	#define _SYS_CHROOT					61
	#define _SYS_USTAT					62
	#define _SYS_DUP2					63
	#define _SYS_GETPPID				64
	#define _SYS_GETPGRP				65
	#define _SYS_SETSID					66
	#define _SYS_SIGACTION				67
	#define _SYS_SGETMASK				68
	#define _SYS_SSETMASK				69
	#define _SYS_SETREUID				70
	#define _SYS_SETREGID				71
	#define _SYS_SIGSUSPEND				72
	#define _SYS_SIGPENDING				73
	#define _SYS_SETHOSTNAME			74
	#define _SYS_SETRLIMIT				75
	#define _SYS_GETRLIMIT				76
	#define _SYS_GETRUSAGE				77
	#define _SYS_GETTIMEOFDAY			78
	#define _SYS_SETTIMEOFDAY			79
	#define _SYS_GETGROUPS				80
	#define _SYS_SETGROUPS				81
	#define _SYS_SELECT					82
	#define _SYS_SYSLINK				83
	#define _SYS_OLDLSTAT				84
	#define _SYS_READLINK				85
	#define _SYS_USELIB					86
	#define _SYS_SWAPON					87
	#define _SYS_REBOOT					88
	#define _SYS_READDIR				89
	#define _SYS_MMAP					90
	#define _SYS_MUNMAP					91
	#define _SYS_SYSLINK                83
	#define _SYS_TRUNCATE        		92
	#define _SYS_FTRUNCATE       		93
	#define _SYS_FCHMOD      			94
	#define _SYS_FCHOWN16        		95
	#define _SYS_GETPRIORITY     		96
	#define _SYS_SETPRIORITY     		97
	#define _UNIMPLEMENTED       		98
	#define _SYS_STATFS      			99
	#define _SYS_FSTATFS     			100
	#define _SYS_IOPERM      			101
	#define _SYS_SOCKETCALL      		102
	#define _SYS_SYSLOG      			103
	#define _SYS_SETITIMER       		104
	#define _SYS_GETITIMER       		105
	#define _SYS_NEWSTAT     			106
	#define _SYS_NEWLSTAT        		107
	#define _SYS_NEWFSTAT        		108
	#define _SYS_UNAME       			109
	#define _SYS_IOPL        			110
	#define _SYS_VHANGUP     			111
	#define _UNIMPLEMENTED       		112
	#define _NOTFOUND        			113
	#define _SYS_WAIT4       			114
	#define _SYS_SWAPOFF     			115
	#define _SYS_SYSINFO     			116
	#define _SYS_IPC     				117
	#define _SYS_FSYNC       			118
	#define _NOTFOUND        			119
	#define _SYS_CLONE       			120
	#define _SYS_SETDOMAINNAME       	121
	#define _SYS_NEWUNAME        		122
	#define _SYS_MODIFY_LDT      		123
	#define _SYS_ADJTIMEX_TIME32     	124
	#define _SYS_MPROTECT        		125
	#define _SYS_SIGPROCMASK     		126
	#define _UNIMPLEMENTED       		127
	#define _SYS_INIT_MODULE     		128
	#define _SYS_DELETE_MODULE       	129
	#define _UNIMPLEMENTED       		130
	#define _SYS_QUOTACTL        		131
	#define _SYS_GETPGID     			132
	#define _SYS_FCHDIR      			133
	#define _SYS_NI_SYSCALL      		134
	#define _SYS_SYSFS       			135
	#define _SYS_PERSONALITY     		136
	#define _UNIMPLEMENTED       		137
	#define _SYS_SETFSUID16      		138
	#define _SYS_SETFSGID16      		139
	#define _SYS_LLSEEK      			140
	#define _SYS_GETDENTS        		141
	#define _SYS_SELECT      			142
	#define _SYS_FLOCK       			143
	#define _SYS_MSYNC       			144
	#define _SYS_READV       			145
	#define _SYS_WRITEV      			146
	#define _SYS_GETSID      			147
	#define _SYS_FDATASYNC       		148
	#define _SYS_NI_SYSCALL      		149
	#define _SYS_MLOCK       			150
	#define _SYS_MUNLOCK     			151
	#define _SYS_MLOCKALL        		152
	#define _SYS_MUNLOCKALL      		153
	#define _SYS_SCHED_SETPARAM      	154
	#define _SYS_SCHED_GETPARAM      	155
	#define _SYS_SCHED_SETSCHEDULER     156
	#define _SYS_SCHED_GETSCHEDULER     157
	#define _SYS_SCHED_YIELD     		158
	#define _SYS_SCHED_GET_PRIORITY_MAX 159
	#define _SYS_SCHED_GET_PRIORITY_MIN 160
	#define _SYS_SCHED_RR_GET_INTERVAL_TIME 161
	#define _SYS_NANOSLEEP_TIME       	162
	#define _SYS_MREMAP      			163
	#define _SYS_SETRESUID     			164
	#define _SYS_GETRESUID     			165
	#define _NOTFOUND        			166
	#define _UNIMPLEMENTED       		167
	#define _SYS_POLL        			168
	#define _UNIMPLEMENTED       		169
	#define _SYS_SETRESGID16     		170
	#define _SYS_GETRESGID16     		171
	#define _SYS_PRCTL       			172
	#define _SYS_RT_SIGRETURN        	173
	#define _SYS_RT_SIGACTION        	174
	#define _SYS_RT_SIGPROCMASK      	175
	#define _SYS_RT_SIGPENDING       	176
	#define _SYS_RT_SIGTIMEDWAIT_TIME32 177
	#define _SYS_RT_SIGQUEUEINFO     	178
	#define _SYS_RT_SIGSUSPEND       	179
	#define _SYS_IA32_PREAD64        	180
	#define _SYS_IA32_PWRITE64       	181
	#define _SYS_CHOWN16     			182
	#define _SYS_GETCWD      			183
	#define _SYS_CAPGET      			184
	#define _SYS_CAPSET      			185
	#define _SYS_SIGALTSTACK     		186
	#define _SYS_SENDFILE        		187
	#define _UNIMPLEMENTED       		188
	#define _UNIMPLEMENTED       		189
	#define _SYS_VFORK       			190
	#define _SYS_GETRLIMIT       		191
	#define _SYS_MMAP_PGOFF      		192
	#define _SYS_IA32_TRUNCATE64     	193
	#define _SYS_IA32_FTRUNCATE64       194
	#define _SYS_STAT64      			195
	#define _SYS_LSTAT64     			196
	#define _SYS_FSTAT64     			197
	#define _SYS_LCHOWN      			198
	#define _SYS_GETUID      			199
	#define _SYS_GETGID      			200
	#define _SYS_GETEUID     			201
	#define _SYS_GETEGID     			202
	#define _SYS_SETREUID        		203
	#define _SYS_SETREGID        		204
	#define _SYS_GETGROUPS       		205
	#define _SYS_SETGROUPS       		206
	#define _SYS_FCHOWN      			207
	#define _SYS_SETRESUID       		208
	#define _SYS_GETRESUID       		209
	#define _SYS_SETRESGID       		210
	#define _SYS_GETRESGID       		211
	#define _SYS_CHOWN       			212
	#define _SYS_SETUID      			213
	#define _SYS_SETGID      			214
	#define _SYS_SETFSUID        		215
	#define _SYS_SETFSGID        		216
	#define _SYS_PIVOT_ROOT      		217
	#define _SYS_MINCORE     			218
	#define _SYS_MADVISE     			219
	#define _SYS_GETDENTS64      		220
	#define _SYS_FCNTL64     			221
	#define _SYS_GETTID      			224
	#define _SYS_IA32_READAHEAD      	225
	#define _SYS_SETXATTR        		226
	#define _SYS_LSETXATTR       		227
	#define _SYS_FSETXATTR       		228
	#define _SYS_GETXATTR        		229
	#define _SYS_LGETXATTR       		230
	#define _SYS_FGETXATTR       		231
	#define _SYS_LISTXATTR       		232
	#define _SYS_LLISTXATTR      		233
	#define _SYS_FLISTXATTR      		234
	#define _SYS_REMOVEXATTR     		235
	#define _SYS_LREMOVEXATTR        	236
	#define _SYS_FREMOVEXATTR        	237
	#define _SYS_TKILL       			238
	#define _SYS_SENDFILE64      		239
	#define _SYS_FUTEX_TIME32        	240
	#define _SYS_SCHED_SETAFFINITY      241
	#define _SYS_SCHED_GETAFFINITY      242
	#define _SYS_SET_THREAD_AREA     	243
	#define _SYS_GET_THREAD_AREA     	244
	#define _SYS_IO_SETUP        		245
	#define _SYS_IO_DESTROY      		246
	#define _SYS_IO_GETEVENTS_TIME32    247
	#define _SYS_IO_SUBMIT       		248
	#define _SYS_IO_CANCEL       		249
	#define _SYS_IA32_FADVISE64      	250
	#define _SYS_EXIT_GROUP      		252
	#define _NOTFOUND        			253
	#define _SYS_EPOLL_CREATE        	254
	#define _SYS_EPOLL_CTL       		255
	#define _SYS_EPOLL_WAIT      		256
	#define _SYS_REMAP_FILE_PAGES       257
	#define _SYS_SET_TID_ADDRESS     	258
	#define _SYS_TIMER_CREATE        	259
	#define _SYS_TIMER_SETTIME32     	260
	#define _SYS_TIMER_GETTIME32     	261
	#define _SYS_TIMER_GETOVERRUN       262
	#define _SYS_TIMER_DELETE        	263
	#define _SYS_CLOCK_SETTIME32     	264
	#define _SYS_CLOCK_GETTIME32     	265
	#define _SYS_CLOCK_GETRES_TIME32    266
	#define _SYS_CLOCK_NANOSLEEP_TIME32 267
	#define _SYS_STATFS64        		268
	#define _SYS_FSTATFS64       		269
	#define _SYS_TGKILL      			270
	#define _SYS_UTIMES_TIME32       	271
	#define _SYS_IA32_FADVISE64_64      272
	#define _UNIMPLEMENTED       		273
	#define _SYS_MBIND       			274
	#define _SYS_GET_MEMPOLICY       	275
	#define _SYS_SET_MEMPOLICY       	276
	#define _SYS_MQ_OPEN     			277
	#define _SYS_MQ_UNLINK       		278
	#define _SYS_MQ_TIMEDSEND_TIME32    279
	#define _SYS_MQ_TIMEDRECEIVE_TIME32 280
	#define _SYS_MQ_NOTIFY       		281
	#define _SYS_MQ_GETSETATTR       	282
	#define _SYS_KEXEC_LOAD      		283
	#define _SYS_WAITID      			284
	#define _SYS_ADD_KEY     			286
	#define _SYS_REQUEST_KEY     		287
	#define _SYS_KEYCTL      			288
	#define _SYS_IOPRIO_SET      		289
	#define _SYS_IOPRIO_GET      		290
	#define _SYS_INOTIFY_INIT        	291
	#define _SYS_INOTIFY_ADD_WATCH      292
	#define _SYS_INOTIFY_RM_WATCH       293
	#define _SYS_MIGRATE_PAGES       	294
	#define _SYS_OPENAT      			295
	#define _SYS_MKDIRAT     			296
	#define _SYS_MKNODAT     			297
	#define _SYS_FCHOWNAT        		298
	#define _SYS_FUTIMESAT_TIME32       299
	#define _SYS_FSTATAT64       		300
	#define _SYS_UNLINKAT        		301
	#define _SYS_RENAMEAT        		302
	#define _SYS_LINKAT      			303
	#define _SYS_SYMLINKAT       		304
	#define _SYS_READLINKAT      		305
	#define _SYS_FCHMODAT        		306
	#define _SYS_FACCESSAT       		307
	#define _SYS_PSELECT6_TIME32     	308
	#define _SYS_PPOLL_TIME32        	309
	#define _SYS_UNSHARE     			310
	#define _SYS_SET_ROBUST_LIST     	311
	#define _SYS_GET_ROBUST_LIST     	312
	#define _SYS_SPLICE      			313
	#define _SYS_IA32_SYNC_FILE_RANGE   314
	#define _SYS_TEE     				315
	#define _SYS_VMSPLICE        		316
	#define _SYS_MOVE_PAGES      		317
	#define _SYS_GETCPU      			318
	#define _SYS_EPOLL_PWAIT     		319
	#define _SYS_UTIMENSAT_TIME32       320
	#define _SYS_SIGNALFD        		321
	#define _SYS_TIMERFD_CREATE      	322
	#define _SYS_EVENTFD     			323
	#define _SYS_IA32_FALLOCATE      	324
	#define _SYS_TIMERFD_SETTIME32      325
	#define _SYS_TIMERFD_GETTIME32      326
	#define _SYS_SIGNALFD4       		327
	#define _SYS_EVENTFD2        		328
	#define _SYS_EPOLL_CREATE1       	329
	#define _SYS_DUP3        			330
	#define _SYS_PIPE2       			331
	#define _SYS_INOTIFY_INIT1       	332
	#define _SYS_PREADV      			333
	#define _SYS_PWRITEV     			334
	#define _SYS_RT_TGSIGQUEUEINFO      335
	#define _SYS_PERF_EVENT_OPEN     	336
	#define _SYS_RECVMMSG_TIME32     	337
	#define _SYS_FANOTIFY_INIT       	338
	#define _SYS_FANOTIFY_MARK       	339
	#define _SYS_PRLIMIT64       		340
	#define _SYS_NAME_TO_HANDLE_AT      341
	#define _SYS_OPEN_BY_HANDLE_AT      342
	#define _SYS_CLOCK_ADJTIME32     	343
	#define _SYS_SYNCFS      			344
	#define _SYS_SENDMMSG        		345
	#define _SYS_SETNS       			346
	#define _SYS_PROCESS_VM_READV       347
	#define _SYS_PROCESS_VM_WRITEV      348
	#define _SYS_KCMP        			349
	#define _SYS_FINIT_MODULE        	350
	#define _SYS_SCHED_SETATTR       	351
	#define _SYS_SCHED_GETATTR       	352
	#define _SYS_RENAMEAT2       		353
	#define _SYS_SECCOMP     			354
	#define _SYS_GETRANDOM       		355
	#define _SYS_MEMFD_CREATE        	356
	#define _SYS_BPF     				357
	#define _SYS_EXECVEAT        		358
	#define _SYS_SOCKET      			359
	#define _SYS_SOCKETPAIR      		360
	#define _SYS_BIND        			361
	#define _SYS_CONNECT     			362
	#define _SYS_LISTEN      			363
	#define _SYS_ACCEPT4     			364
	#define _SYS_GETSOCKOPT      		365
	#define _SYS_SETSOCKOPT      		366
	#define _SYS_GETSOCKNAME     		367
	#define _SYS_GETPEERNAME     		368
	#define _SYS_SENDTO      			369
	#define _SYS_SENDMSG     			370
	#define _SYS_RECVFROM        		371
	#define _SYS_RECVMSG     			372
	#define _SYS_SHUTDOWN        		373
	#define _SYS_USERFAULTFD     		374
	#define _SYS_MEMBARRIER      		375
	#define _SYS_MLOCK2      			376
	#define _SYS_COPY_FILE_RANGE     	377
	#define _SYS_PREADV2     			378
	#define _SYS_PWRITEV2        		379
	#define _SYS_PKEY_MPROTECT       	380
	#define _SYS_PKEY_ALLOC      		381
	#define _SYS_PKEY_FREE       		382
	#define _SYS_STATX       			383
	#define _SYS_ARCH_PRCTL      		384
	#define _SYS_IO_PGETEVENTS_TIME32   385
	#define _SYS_RSEQ        			386
	#define _SYS_SEMGET      			393
	#define _SYS_SEMCTL      			394
	#define _SYS_SHMGET      			395
	#define _SYS_SHMCTL      			396
	#define _SYS_SHMAT       			397
	#define _SYS_SHMDT       			398
	#define _SYS_MSGGET      			399
	#define _SYS_MSGSND      			400
	#define _SYS_MSGRCV      			401
	#define _SYS_MSGCTL      			402
	#define _SYS_CLOCK_GETTIME       	403
	#define _SYS_CLOCK_SETTIME       	404
	#define _SYS_CLOCK_ADJTIME       	405
	#define _SYS_CLOCK_GETRES       	406
	#define _SYS_CLOCK_NANOSLEEP     	407
	#define _SYS_TIMER_GETTIME       	408
	#define _SYS_TIMER_SETTIME       	409
	#define _SYS_TIMERFD_GETTIME     	410
	#define _SYS_TIMERFD_SETTIME     	411
	#define _SYS_UTIMENSAT       		412
	#define _SYS_PSELECT6        		413
	#define _SYS_PPOLL       			414
	#define _SYS_IO_PGETEVENTS       	416
	#define _SYS_RECVMMSG        		417
	#define _SYS_MQ_TIMEDSEND        	418
	#define _SYS_MQ_TIMEDRECEIVE     	419
	#define _SYS_SEMTIMEDOP      		420
	#define _SYS_RT_SIGTIMEDWAIT     	421
	#define _SYS_FUTEX       			422
	#define _SYS_SCHED_RR_GET_INTERVAL  423
	#define _SYS_PIDFD_SEND_SIGNAL      424
	#define _SYS_IO_URING_SETUP      	425
	#define _SYS_IO_URING_ENTER      	426
	#define _SYS_IO_URING_REGISTER      427
	#define _SYS_OPEN_TREE       		428
	#define _SYS_MOVE_MOUNT      		429
	#define _SYS_FSOPEN      			430
	#define _SYS_FSCONFIG        		431
	#define _SYS_FSMOUNT     			432
	#define _SYS_FSPICK      			433
	#define _SYS_PIDFD_OPEN      		434
	#define _SYS_CLONE3      			435
	#define _SYS_CLOSE_RANGE     		436
	#define _SYS_OPENAT2     			437
	#define _SYS_PIDFD_GETFD     		438
	#define _SYS_FACCESSAT2      		439
	#define _SYS_PROCESS_MADVISE     	440
	#define _SYS_EPOLL_PWAIT2        	441
	#define _SYS_MOUNT_SETATTR      	442
	#define _SYS_QUOTACTL_FD     		443
	#define _SYS_LANDLOCK_CREATE_RULESET 444
	#define _SYS_LANDLOCK_ADD_RULE      445
	#define _SYS_LANDLOCK_RESTRICT_SELF 446
	#define _SYS_MEMFD_SECRET        	447
	#define _SYS_PROCESS_MRELEASE       448
	#define _SYS_FUTEX_WAITV     		449
	#define _SET_MEMPOLICY_HOME_NOD		-1
#elif defined(__x86_64__)
	#define MAX_REGISTER 6
	#define SYSCALL_REG "rax"
	#define EXECUTE_SYSCALL "syscall"

	/* x86_64 C-ABIV Calling Convension */
    #define __RAX__ "rax"
    #define __RDI__ "rdi"
    #define __RSI__ "rsi"
    #define __RDX__ "rdx"
    #define __R10__ "r10"
    #define __R8__ "r8"
    #define __R9__ "r9"
    #define __RBX__ "rbx"
    #define __RCX__ "rcx"
    #define __RBP__ "rbp"
    #define __R15__ "r15"
    #define __R14__ "r14"
    #define __R13__ "r13"
    #define __R12__ "r12"
    #define __R11__ "r11"
    #define __RSP__ "rsp"

	/* x86_64 syscalls */
    #define _SYS_READ                   0
    #define _SYS_WRITE                  1
    #define _SYS_OPEN                   2
    #define _SYS_CLOSE                  3
    #define _SYS_STAT                   4
    #define _SYS_FSTAT                  5
    #define _SYS_LSTAT                  6
    #define _SYS_POLL                   7
    #define _SYS_LSEEK                  8
    #define _SYS_MMAP                   9
    #define _SYS_MPROTECT               10
    #define _SYS_MUNMAP                 11
    #define _SYS_BRK                    12
    #define _SYS_RT_SIGACTION           13
    #define _SYS_RT_SIGPROCMASK         14
    #define _SYS_RT_SIGRETURN           15
    #define _SYS_IOCTL                  16
    #define _SYS_PREAD64                17
    #define _SYS_PWRITE64               18
    #define _SYS_READV                  19
    #define _SYS_WRITEV                 20
    #define _SYS_ACCESS                 21
    #define _SYS_PIPE                   22
    #define _SYS_SELECT                 23
    #define _SYS_SCHED_YIELD            24
    #define _SYS_MREMAP                 25
    #define _SYS_MSYNC                  26
    #define _SYS_MINCORE                27
    #define _SYS_MADVISE                28
    #define _SYS_SHMGET                 29
    #define _SYS_SHMAT                  30
    #define _SYS_SHMTL                  31
    #define _SYS_DUP                    32
    #define _SYS_DUP2                   33
    #define _SYS_PAUSE                  34
    #define _SYS_NANOSLEEP              35
    #define _SYS_GETITIMER              36
    #define _SYS_ALARM                  37
    #define _SYS_SETITIMER              38
    #define _SYS_GETPID                 39
    #define _SYS_SENDFILE               40
    #define _SYS_SOCKET                 41
    #define _SYS_CONNECT                42
    #define _SYS_ACCEPT                 43
    #define _SYS_SENDTO                 44
    #define _SYS_RECVFROM               45
    #define _SYS_SENDMSG                46
    #define _SYS_RECVMSG                47
    #define _SYS_SHUTDOWN               48
    #define _SYS_BIND                   49
    #define _SYS_LISTEN                 50
    #define _SYS_GETSOCKNAME            51
    #define _SYS_GETPEERNAME            52
    #define _SYS_SOCKETPAIR             53
    #define _SYS_SETSOCKOPT             54
    #define _SYS_GETSOCKOPT             55
    #define _SYS_CLONE                  56
    #define _SYS_FORK                   57
    #define _SYS_VFORK                  58
    #define _SYS_EXECVE                 59
    #define _SYS_EXIT                   60
    #define _SYS_WAIT4                  61
    #define _SYS_KILL                   62
    #define _SYS_UNAME                  63
    #define _SYS_SEMGET                 64
    #define _SYS_SEMOP                  65
    #define _SYS_SEMCTL                 66
    #define _SYS_SHMDT                  67
    #define _SYS_MSGGET                 68
    #define _SYS_MSGSND                 69
    #define _SYS_MSGRCV                 70
    #define _SYS_MSGCTL                 71
    #define _SYS_FCNTL                  72
    #define _SYS_FLOCK                  73
    #define _SYS_FSYNC                  74
    #define _SYS_FDATASYNC              75
    #define _SYS_TRUNCATE               76
    #define _SYS_FTRUNCATE              77
    #define _SYS_GETDENTS               78
    #define _SYS_GETCWD                 79
    #define _SYS_CHDIR                  80
    #define _SYS_FCHDIR                 81
    #define _SYS_RENAME                 82
    #define _SYS_MKDIR                  83
    #define _SYS_RMDIR                  84
    #define _SYS_CREAT                  85
    #define _SYS_LINK                   86
    #define _SYS_UNLINK                 87
    #define _SYS_SYMLINK                88
    #define _SYS_READLINK               89
    #define _SYS_CHMOD                  90
    #define _SYS_FCHMOD                 91
    #define _SYS_CHOWN                  92
    #define _SYS_FCHOWN                 93
    #define _SYS_LCHOWN                 94
    #define _SYS_UMASK                  95
    #define _SYS_GETTIMEOFDAT           96
    #define _SYS_GETRLIMIT              97
    #define _SYS_GETRUSAGE              98
    #define _SYS_SYSINFO                99
    #define _SYS_TIMES                  100
    #define _SYS_PTRACE                 101
    #define _SYS_GETUID                 102
    #define _SYS_SYSLOG                 103
    #define _SYS_GETGID                 104
    #define _SYS_SETUID                 105
    #define _SYS_SETGID                 106
    #define _SYS_GETEUID                107
    #define _SYS_GETEGID                108
    #define _SYS_SETPGID                109
    #define _SYS_GETPPID                110
    #define _SYS_GETPGRP                111
    #define _SYS_SETSID                 112
    #define _SYS_SETREUID               113
    #define _SYS_SETREGID               114
    #define _SYS_GETGROUPS              115
    #define _SYS_SETGROUPS              116
    #define _SYS_SETRESUID              117
    #define _SYS_GETRESUID              118
    #define _SYS_SETRESGID              119
    #define _SYS_GETRESGID              120
    #define _SYS_GETPGID                121
    #define _SYS_SETFSUID               122
    #define _SYS_SETFSGID               123
    #define _SYS_GETSID                 124
    #define _SYS_CAPGET                 125
    #define _SYS_CATSET                 126
    #define _SYS_RT_SIGPENDING          127
    #define _SYS_RT_SIGTIMEDWAIT        128
    #define _SYS_RT_SIGQUEUEINFO        129
    #define _SYS_RT_SIGSUSPEND          130
    #define _SYS_SIGALTSTACK            131
    #define _SYS_UTIME                  132
    #define _SYS_MKNOD                  133
    #define _SYS_USELIB                 134
    #define _SYS_PERSONALITY            135
    #define _SYS_USTAT                  136
    #define _SYS_STATFS                 137
    #define _SYS_FSTATFS                138
    #define _SYS_SYSFS                  139
    #define _SYS_GETPRIORITY            140
    #define _SYS_SETPRIORITY            141
    #define _SYS_SCHED_SETPARAM         142
    #define _SYS_SCHED_GETPARAM         143
    #define _SYS_SCHED_SETSCHEDULER     144
    #define _SYS_SCHED_GETSCHEDULAR     145
    #define _SYS_SCHED_GET_PRIORITY_MAX 146
    #define _SYS_SCHED_GET_PRIORITY_MIN 147
    #define _SYS_SCHED_RR_GET_INTERVAL  148
    #define _SYS_MLOCK                  149
    #define _SYS_MINLOCK                150
    #define _SYS_MLOCKALL               151
    #define _SYS_MUNLOCKALL             152
    #define _SYS_VHANGUP                153
    #define _SYS_MODIFY_LDT             154
    #define _SYS_PIVOT_ROOT             155
    #define _SYS__SYSCTL                156
    #define _SYS_PRCTL                  157
    #define _SYS_ARCH_PRCTL             158
    #define _SYS_ADJTIMEX               159
    #define _SYS_SETRLIMIT              160
    #define _SYS_CHROOT                 161
    #define _SYS_SYNC                   162
    #define _SYS_ACCT                   163
    #define _SYS_SETTIMEOFDAY           164
    #define _SYS_MOUNT                  165
    #define _SYS_UMOUNT2                166
    #define _SYS_SWAPON                 167
    #define _SYS_SWAPOFF                168
    #define _SYS_REBOOT                 169
    #define _SYS_SETHOSTNAME            170
    #define _SYS_SETDOMAINNAME          171
    #define _SYS_IOPL                   172
    #define _SYS_IOPERM                 173
    #define _SYS_CREATE_MODULE          174
    #define _SYS_INIT_MODULE            175
    #define _SYS_DELETE_MODULE          176
    #define _SYS_GET_KERNEL_SYMS        177
    #define _SYS_QUERY_MODULE           178
    #define _SYS_QUOTACTL               179
    #define _SYS_NFSSERVCTL             180
    #define _SYS_GETPMSG                181
    #define _SYS_PUTPMSG                182
    #define _SYS_AFS_SYSCALL            183
    #define _SYS_TUXCALL                184
    #define _SYS_SECURITY               185
    #define _SYS_GETTID                 186
    #define _SYS_READAHEAD              187
    #define _SYS_SETXATTR               188
    #define _SYS_LSETXATTR              189
    #define _SYS_FSETXATTR              190
    #define _SYS_GETXATTR               191
    #define _SYS_LGETXATTR              192
    #define _SYS_FGETXATTR              193
    #define _SYS_LISTXATTR              194
    #define _SYS_LLISTXATTR             195
    #define _SYS_FLISTXATTR             196
    #define _SYS_REMOVEXATTR            197
    #define _SYS_LREMOVEXATTR           198
    #define _SYS_FREMOVEXATTR           199
    #define _SYS_TKILL                  200
    #define _SYS_TIME                   201
    #define _SYS_FUTEX                  202
    #define _SYS_SCHED_SETAFFINITY      203
    #define _SYS_SCHED_GETAFFINITY      204
    #define _SYS_SET_THREAD_AREA        205
    #define _SYS_IO_SETUP               206
    #define _SYS_IO_DESTROY             207
    #define _SYS_IO_GETEVENTS           208
    #define _SYS_IO_SUBMIT              209
    #define _SYS_IO_CANCEL              210
    #define _SYS_GET_THREAD_AREA        211
    #define _SYS_LOOKUP_DCOOKIE         212
    #define _SYS_EPOLL_CREATE           213
    #define _SYS_EPOLL_CTL_OLD          214
    #define _SYS_EPOLL_WAIT_OLD         215
    #define _SYS_REMAP_FILE_PAGES       216
    #define _SYS_GETDENTS64             217
    #define _SYS_SET_TID_ADDRESS        218
    #define _SYS_RESTART_SYSCALL        219
    #define _SYS_SETTIMEDOP             220
    #define _SYS_FADVISE64              221
    #define _SYS_TIMER_CREATE           222
    #define _SYS_TIMER_SETTIME          223
    #define _SYS_TIMER_GETTIME          224
    #define _SYS_TIMER_GETOVERRUN       225
    #define _SYS_TIMER_DELETE           226
    #define _SYS_CLOCK_SETTIME          227
    #define _SYS_CLOCK_GETTIME          228
    #define _SYS_CLOCK_GETRES           229
    #define _SYS_CLOCK_NANOSLEEP        230
    #define _SYS_EXIT_GROUP             231
    #define _SYS_EPOLL_WAIT             232
    #define _SYS_EPOLL_CTL              233
    #define _SYS_TGKILL                 234
    #define _SYS_UTIMES                 235
    #define _SYS_VSERVER                236
    #define _SYS_MBIND                  237
    #define _SYS_SET_MEMPOLICY          238
    #define _SYS_GET_MEMPOLICY          239
    #define _SYS_MQ_OPEN                240
    #define _SYS_MQ_UNLINK              241
    #define _SYS_MQ_TIMEDSEND           242
    #define _SYS_MQ_TIMEDRECEIVE        243
    #define _SYS_MQ_NOTIFY              244
    #define _SYS_MQ_GETSETATTR          245
    #define _SYS_KEXEC_LOAD             246
    #define _SYS_WAITID                 247
    #define _SYS_ADD_KEY                248
    #define _SYS_REQUEST_KEY            249
    #define _SYS_KEYCTL                 250
    #define _SYS_IOPRIO_SET             251
    #define _SYS_IOPRIO_GET             252
    #define _SYS_INOTIFY_INIT           253
    #define _SYS_INOTIFY_ADD_WATCH      254
    #define _SYS_INOTIFY_RM_WATCH       255
    #define _SYS_MIGRATE_PAGES          256
    #define _SYS_OPENAT                 257
    #define _SYS_MKDIRAT                258
    #define _SYS_MKNODAT                259
    #define _SYS_FCHOWNAT               260
    #define _SYS_FUTIMESAY              261
    #define _SYS_NEWFSTATAT             262
    #define _SYS_UNLINKAT               263
    #define _SYS_RENAMEAT               264
    #define _SYS_LINKAT                 265
    #define _SYS_SYMLINKAT              266
    #define _SYS_READLINKAT             267
    #define _SYS_FCHMODAT               268
    #define _SYS_FACCESSAT              269
    #define _SYS_PSELECT6               270
    #define _SYS_PPOLL                  271
    #define _SYS_UNSHARE                272
    #define _SYS_SET_ROBUST_LIST        273
    #define _SYS_GET_ROBUST_LIST        274
    #define _SYS_SPLICE                 275
    #define _SYS_TEE                    276
    #define _SYS_SYNC_FILE_RANGE        277
    #define _SYS_VMSPLICE               278
    #define _SYS_MOVE_PAGES             279
    #define _SYS_UTIMENSAT              280
    #define _SYS_EPOLL_PWAIT            281
    #define _SYS_SIGNALFD               282
    #define _SYS_TIMERFD_CREATE         283
    #define _SYS_EVENTFD                284
    #define _SYS_FALLOCATE              285
    #define _SYS_TIMERFD_SETTIME        286
    #define _SYS_TIMERFD_GETTIME        287
    #define _SYS_ACCEPT4                288
    #define _SYS_SIGNALFD4              289
    #define _SYS_EVENTFD2               290
    #define _SYS_EPOLL_CREATE1          291
    #define _SYS_DUP3                   292
    #define _SYS_PIPE2                  293
    #define _SYS_INOTIFY_INIT1          294
    #define _SYS_PREADV                 295
    #define _SYS_PWRITEV                296
    #define _SYS_RT_TGSIGQUEUEINFO      297
    #define _SYS_PERF_EVENT_OPEN        298
    #define _SYS_RECVMMSG               299
    #define _SYS_FANOTIFY_INIT          300
    #define _SYS_FANOTIFY_MARK          301
    #define _SYS_PRLIMIT64              302
    #define _SYS_NAME_TO_HANDLE_AT      303
    #define _SYS_OPEN_BY_HANDLE_AT      304
    #define _SYS_CLOCK_ADJTIME          305
    #define _SYS_SYNCFS                 306
    #define _SYS_SENDMMSG               307
    #define _SYS_SETNS                  308
    #define _SYS_GETCPU                 309
    #define _SYS_PROCESS_VM_READV       310
    #define _SYS_PROVESS_VM_WRITEV      311
    #define _SYS_KCMP                   312
    #define _SYS_FINIT_MODULE           313
    #define _SYS_SCHED_SETATTR          314
    #define _SYS_SCHED_GETATTR          315
    #define _SYS_RENAMEAT2              316
    #define _SYS_SECCOMP                317
    #define _SYS_GETRANDOM              318
    #define _SYS_MEMFD_CREATE           319
    #define _SYS_KEXEC_FILE_LOAD        320
    #define _SYS_BPF                    321
    #define _STUB_EXECVEAT              322
    #define _USERFAULTFD                323
    #define _MEMBARRIER                 324
    #define _MLOCK2                     325
    #define _COPY_FILE_RANGE            326
    #define _PREADV2                    327
    #define _PWRITEV2                   328
    #define _PKEY_MPROTECT              329
    #define _PKEY_ALLOC                 330
    #define _PKEY_FREE                  331
    #define _STATX                      332
    #define _IO_PGETEVENTS              333
    #define _RSEQ                       334
    #define _PKEY_MPROTECT2             335

	/* x86_64 syscall wrappers */
	long __sys_mmap(long arg1, long arg2, long arg3, long arg4, long arg5, long arg6);

#elif defined(__riscv)
	#define MAX_REGISTER 8
	#define SYSCALL_REG "a7"
	#define EXECUTE_SYSCALL "ecall"
#elif defined(__aarch64__)
	#define MAX_REGISTER 8
	#define SYSCALL_REG "x8"
	#define EXECUTE_SYSCALL "svc #0"
#elif defined(__arm__)
	#define MAX_REGISTER 4
	#define SYSCALL_REG "r7"
	#define EXECUTE_SYSCALL "svc #0"
#elif defined(_WIN64)
	#define MAX_REGISTER 4
	#define SYSCALL_REG "rcx"
	#define EXECUTE_SYSCALL "syscall"
#else
	#define MAX_REGISTER 0
	#define SYSCALL_REG 0
	#define EXECUTE_SYSCALL 0
#endif

